name = "imgwrap"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir="build"

kv_namespaces = [
  { binding = "KV", preview_id = "xxx", id = "xxx" }
]

r2_buckets = [
  { binding = "R2", bucket_name = "xxx"}
]